import pygame

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 800
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

FPS = 60

BLOCK_SIZE = 16
# 16 x 16 blocks

MOVE_LEFT_KEY = pygame.K_LEFT
MOVE_RIGHT_KEY = pygame.K_RIGHT
JUMP_KEY = pygame.K_UP